import type { Node, Edge } from 'reactflow';

export function generateWakitCode(nodes: Node[], edges: Edge[]): string {
    const escapeStr = (str: string) => str.replace(/\\\\/g, '\\\\\\\\').replace(/'/g, "\\\\\\'").replace(/\\n/g, '\\\\n');
    let code = `/**
 * Generated by WAKit Studio
 * Creator: Atharv Hatwar
 */
import { createClient, rateLimitMiddleware } from '@atharvh01/wakit';

const client = await createClient({ auth: './session' });
`;

    // Process Rate Limit Nodes (Global Configs)
    const rateLimitNodes = nodes.filter(n => n.type === 'rateLimitNode');
    for (const rl of rateLimitNodes) {
        const max = rl.data.max || '10';
        const window = rl.data.window || '60000';
        code += `// Apply Global Rate Limiting\n`;
        code += `client.useIncoming(rateLimitMiddleware({ maxPerWindow: ${max}, windowMs: ${window} }));\n\n`;
    }

    // Better recursive generation with cycle detection
    const generateNodeTree = (nodeId: string, handleId: string | null, jidTarget: string, indent: string, visited: Set<string>): string => {
        if (visited.has(nodeId)) {
            return `${indent}// Cycle detected, terminating flow here.\n`;
        }
        visited.add(nodeId);

        let output = '';
        // Find edges leaving this node/handle
        const outEdges = edges.filter(e => e.source === nodeId && (handleId ? e.sourceHandle === handleId : true));
        
        for (const edge of outEdges) {
            const nextNode = nodes.find(n => n.id === edge.target);
            if (!nextNode) continue;

            if (nextNode.type === 'actionNode') {
                const messageText = nextNode.data.text || '';
                output += `${indent}await client.sendMessage(${jidTarget}, { text: '${escapeStr(messageText)}' });\n`;
                output += generateNodeTree(nextNode.id, null, jidTarget, indent, new Set(visited));
            } else if (nextNode.type === 'mediaNode') {
                const url = nextNode.data.url || '';
                const caption = nextNode.data.caption || '';
                const capStr = caption ? `, caption: '${escapeStr(caption)}'` : '';
                output += `${indent}await client.sendMessage(${jidTarget}, { image: { url: '${escapeStr(url)}' }${capStr} });\n`;
                output += generateNodeTree(nextNode.id, null, jidTarget, indent, new Set(visited));
            } else if (nextNode.type === 'pollNode') {
                const question = nextNode.data.question || '';
                const optionsStr = nextNode.data.options || '';
                const optionsArr = optionsStr.split(',').map((o: string) => `'${escapeStr(o.trim())}'`);
                output += `${indent}await client.sendMessage(${jidTarget}, { \n`;
                output += `${indent}    poll: { name: '${escapeStr(question)}', values: [${optionsArr.join(', ')}], selectableCount: 1 }\n`;
                output += `${indent}});\n`;
                output += generateNodeTree(nextNode.id, null, jidTarget, indent, new Set(visited));
            } else if (nextNode.type === 'delayNode') {
                const ms = parseInt(nextNode.data.ms) || 0;
                if (ms > 0) {
                    output += `${indent}await new Promise(r => setTimeout(r, ${ms}));\n`;
                }
                output += generateNodeTree(nextNode.id, null, jidTarget, indent, new Set(visited));
            } else if (nextNode.type === 'conditionNode') {
                const keyword = (nextNode.data.keyword || '').toLowerCase();
                output += `${indent}if (text.includes('${escapeStr(keyword)}')) {\n`;
                output += generateNodeTree(nextNode.id, 'true', jidTarget, indent + '    ', new Set(visited));
                output += `${indent}} else {\n`;
                output += generateNodeTree(nextNode.id, 'false', jidTarget, indent + '    ', new Set(visited));
                output += `${indent}}\n`;
            } else {
                // CatchAllNode just passes through if reached from elsewhere
                output += generateNodeTree(nextNode.id, null, jidTarget, indent, new Set(visited));
            }
        }
        return output;
    };

    // Process Cron Nodes
    const cronNodes = nodes.filter(n => n.type === 'cronNode');
    if (cronNodes.length > 0) {
        for (const cron of cronNodes) {
            const cronExpr = cron.data.cron || '* * * * *';
            const hasEdges = edges.some(e => e.source === cron.id);
            if (hasEdges) {
                code += `client.scheduler.cron('${cronExpr}', async () => {\n`;
                code += generateNodeTree(cron.id, null, '/* TARGET JID HERE */', '    ', new Set());
                code += `});\n\n`;
            }
        }
    }

    // Process Trigger Nodes (Message Flow)
    const triggers = nodes.filter(n => n.type === 'triggerNode');
    const catchAlls = nodes.filter(n => n.type === 'catchAllNode');
    
    if (triggers.length > 0 || catchAlls.length > 0) {
        code += `client.useIncoming(async (ctx, next) => {\n`;
        code += `    const msg = ctx.message.message;\n`;
        code += `    const text = (msg?.conversation || msg?.extendedTextMessage?.text || '').toLowerCase().trim();\n\n`;

        for (const trigger of triggers) {
            const keyword = trigger.data.keyword || '';
            const hasEdges = edges.some(e => e.source === trigger.id);
            
            if (hasEdges && keyword) {
                code += `    if (text.startsWith('${escapeStr(keyword.toLowerCase())}')) {\n`;
                code += generateNodeTree(trigger.id, null, 'ctx.remoteJid', '        ', new Set());
                code += `        ctx.drop = true; // Stop processing further middlewares\n`;
                code += `        return;\n`;
                code += `    }\n\n`;
            }
        }
        
        // Catch-all triggers fallback logic
        if (catchAlls.length > 0) {
            code += `    // Catch-All Triggers\n`;
            for (const catchAll of catchAlls) {
                const hasEdges = edges.some(e => e.source === catchAll.id);
                if (hasEdges) {
                    code += generateNodeTree(catchAll.id, null, 'ctx.remoteJid', '    ', new Set());
                }
            }
            code += `    ctx.drop = true;\n    return;\n\n`;
        }

        code += `    await next();\n});\n\n`;
    }

    code += `await client.connect();\n`;
    
    return code;
}
